import storage from 'utils/functions/storage';

export default {
  baseUrl: 'https://api.vedabuilder.com',
  version: 'api/v1',
  endpoint: {
    auth: 'auth',
    sections: 'sections',
    sections_categories: 'categories',
    sections_changelogs: 'changelogs',
    addons: 'addons',
    pages: 'pages',
    pages_tags: 'tags',
    pages_categories: 'categories',
    users: 'users',
    'shopify-connections': 'shopify-connections',
    me_medias: 'command/medias/me',
    admin_medias: 'command/medias/admin',
    themes: 'themes',
    themes_tags: 'tags',
    themes_categories: 'categories',
    atom: 'atom',
    product: 'product',
    mega_menus: 'mega-menus',
    dev: 'dev',
    admin: 'admin',
    clients: 'clients',
  },
  timeout: 30000,
  apiFake: storage.getItem('API_FAKE') === 'true',
  env: (storage.getItem('env') as 'dev' | 'prod') || 'prod',
  socketAPIForSyncShopify: 'https://socket.vedabuilder.com',
  socketAPIForImportThemeAtomToClientService: 'https://clients-websocket.vedabuilder.com',
  socketEndpoint: 'veda-ws',
  forceReload: storage.getItem('FORCE_RELOAD') === 'true',
};
