import { MenuItem } from 'components/Navigation/Navigation';
import { v4 } from 'uuid';

export const getMenu = (shopName: string): MenuItem[] => [
  {
    id: v4(),
    href: `https://${shopName}/admin/orders`,
    label: 'Orders',
    icon: 'box',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/products`,
    label: 'Products',
    icon: 'shopping-bag',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/products/inventory`,
    label: 'Inventory',
    icon: 'cart-arrow-down',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/products/transfers`,
    label: 'Transfers',
    icon: 'external-link',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/collections`,
    label: 'Collections',
    icon: 'tags',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/gift_cards`,
    label: 'Gift cards',
    icon: 'gift',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/price_lists`,
    label: 'Price Lists',
    icon: 'clipboard-list-check' as any,
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/customers`,
    label: 'Customers',
    icon: 'users',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/dashboards`,
    label: 'Analytics',
    icon: 'analytics' as any,
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/marketing`,
    label: 'Marketing',
    icon: 'bullseye-arrow' as any,
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/discounts`,
    label: 'Discounts',
    icon: 'badge-percent' as any,
    isReactRouter: false,
    hasDivider: true,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/general`,
    label: 'Store details',
    icon: 'store',
    isReactRouter: false,
    textHeader: 'Settings',
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/plan`,
    label: 'Plan',
    icon: 'list-alt',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/billing`,
    label: 'Billing',
    icon: 'badge-dollar' as any,
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/account`,
    label: 'Users and permissions',
    icon: 'user',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/payments`,
    label: 'Payments',
    icon: 'credit-card-front',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/checkout`,
    label: 'Checkout and accounts',
    icon: 'shopping-cart',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/shipping`,
    label: 'Shipping and delivery',
    icon: 'shipping-fast',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/taxes`,
    label: 'Taxes and duties',
    icon: 'percentage',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/locations`,
    label: 'Locations',
    icon: 'map-marker-alt',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/gift_cards`,
    label: 'Gift cards',
    icon: 'gift-card',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/markets`,
    label: 'Markets',
    icon: 'globe',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/apps`,
    label: 'Apps and sales channels',
    icon: 'layer-plus',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/domains`,
    label: 'Domains',
    icon: 'external-link-square',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/customer_events`,
    label: 'Customer events',
    icon: 'location-arrow',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/branding`,
    label: 'Brand',
    icon: 'shapes',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/notifications`,
    label: 'Notifications',
    icon: 'bell',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/metafields`,
    label: 'Metafields',
    icon: 'database',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/files`,
    label: 'Files',
    icon: 'paperclip',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/languages`,
    label: 'Languages',
    icon: 'language',
    isReactRouter: false,
  },
  {
    id: v4(),
    href: `https://${shopName}/admin/settings/legal`,
    label: 'Policies',
    icon: 'file-alt',
    isReactRouter: false,
  },
];
