import {
  watchApproveThemeDraft,
  watchCommitThemeDraft,
  watchCreateThemeAtom,
  watchCreateThemeDraft,
  watchCreateUserThemeCategory,
  watchDeleteThemeAtom,
  watchDeleteThemeDraft,
  watchForkThemeAtom,
  watchGetCategoriesOfThemeProduct,
  watchGetPagesTemplate,
  watchGetThemesAtom,
  watchGetThemesDraft,
  watchHotfixThemeAtom,
  watchLoadmorePagesTemplate,
  watchPublishThemeAtom,
  watchRejectThemeDraft,
  watchAppendPageToThemeAtom,
  watchAppendPageToThemeDraft,
  watchLoadmoreThemesAtom,
  watchLoadmoreThemesDraft,
} from './store/sagas';

export * from './Themes';

export const sagasThemeManagement = [
  watchApproveThemeDraft,
  watchCommitThemeDraft,
  watchCreateThemeAtom,
  watchCreateThemeDraft,
  watchCreateUserThemeCategory,
  watchDeleteThemeAtom,
  watchDeleteThemeDraft,
  watchForkThemeAtom,
  watchGetCategoriesOfThemeProduct,
  watchGetPagesTemplate,
  watchGetThemesAtom,
  watchGetThemesDraft,
  watchHotfixThemeAtom,
  watchLoadmorePagesTemplate,
  watchPublishThemeAtom,
  watchRejectThemeDraft,
  watchAppendPageToThemeAtom,
  watchAppendPageToThemeDraft,
  watchLoadmoreThemesAtom,
  watchLoadmoreThemesDraft,
];
